APP_PACKAGE_NAME = '<YOUR APP PACKAGE NAME>'
TOTAL_BATCH_API_MODE = 5
REVIEW_COUNT_PER_BATCH_SCRAPING_MODE = 50
TOTAL_BATCH_SCRAPING_MODE = 100
IS_AUTO_PILOT_MODE_ON = False

SERVICE_ACCOUNT_FILE = 'creds.json'
ANDROID_PUBLISHER_API_SCOPE = ['https://www.googleapis.com/auth/androidpublisher']
SERVICE_NAME_ANDROID_PUBLISHER = 'androidpublisher'
ANDROID_PUBLISHER_API_VERSION = 'v3'

OLLAMA_API_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3"

DUMPED_REVIEWS_JSON_FILE = 'input/reviews_from_scrapping.json'

SKIPPER_KEYWORDS = ["<KEYWORDS YOU WANT TO SKIP>"]